# Grafana MCP server https://github.com/grafana/mcp-grafana
version: '3.9'
# 执行脚本；docker-compose -f docker-compose-grafana-mcp.yml up -d
services:
  # 监控服务 mcp https://github.com/grafana/mcp-grafana
  grafana-mcp:
    image: mcp/grafana
    container_name: grafana-mcp
    ports:
      - "8000:8000"
    environment:
      - GRAFANA_URL=http://grafana:4000
      - GRAFANA_API_KEY=glsa_ELtYrUYyZUsZQSrwUmTC46ndtYacghyc_88cd15c4
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
